### The configuration file of anonychating_server
###
### Copy this file to `config.toml` and start editing.


[Telexide]
bot_token = "" # Your bot token.

[Warp]
server_ip = [127, 0, 0, 1] # to public this API, change `127, 0, 0, 1` to `0, 0, 0, 0`.
server_port = 3030